services:
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "2036:1883"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    environment:
      - TZ=Europe/Berlin
